services:
  - type: web
    name: nostr-algo-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
